### ISSUE TITLE
is-valid-path documentation and readme reference

### ISSUE THREAD

**Issue by danielmirchandani** [playerony/indexeddb-fs#44]
I was trying to import an SSH identity in https://chromium.googlesource.com/apps/libapps/+/HEAD/nassh. The identity files contained a "@" character, but the error message "path is invalid" didn't give me any hints to which part was invalid. I finally landed on `isValidPath` in https://github.com/playerony/indexeddb-fs/blob/main/lib/utils/functions/is-valid-path/is-valid-path.function.ts, then interpreted the regular expression in my head (probably badly) to discover what was wrong.

Can we include the regular expression in the error message?

Can we document the valid path logic in the main README? I feel like this is relevant information for users of this library.

**Comment by playerony** [comment]
I will try to cover this change. I have a plan to fix all issues in this package soon, so stay tuned!

**Comment by danielmirchandani** [comment]
Do you have a link to the commit that fixed this issue?  https://github.com/playerony/indexeddb-fs/commit/51a0c8313de3956ad48cf04076a4219b07420db2 is the only change to this file since I filed this issue, and it only reformatted the file.
